version: 0.0.{build}
configuration:
- Release
- Debug
platform:
- Win32
- x64
clone_folder: c:\SLBuild\cabl
init:
- cmd: choco install doxygen.install
build_script:
- cmd: >-
    echo Running cmake...

    echo Building %CONFIGURATION% - %PLATFORM%

    cd c:\SLBuild\cabl

    mkdir build-%PLATFORM%

    pushd build-%PLATFORM%

    if %PLATFORM% == x64 (cmake -G "Visual Studio 14 2015 Win64" -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON ..) else (cmake -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=ON ..)

    cd ..

    cmake --build build-%PLATFORM% --config %CONFIGURATION%
before_test:
- cmd: >-
    cd c:\SLBuild\cabl\build-%PLATFORM%\test\%CONFIGURATION%\

    unit-tests.exe -s -r junit -o test-report.junit.xml
after_test:
- ps: >-
    # upload results to AppVeyor

    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path c:\SLBuild\cabl\build-$($env:PLATFORM)\test\$($env:CONFIGURATION)\test-report.junit.xml))
artifacts:
- path: build-$(PLATFORM)/$(CONFIGURATION)/cabl.lib
  name: cabl (static)
- path: build-$(PLATFORM)/$(CONFIGURATION)/cabl.dll
  name: cabl (dll)
deploy:
- provider: Environment
  name: cabl-win-x64
  on:
    branch: develop
    CONFIGURATION: Release
    PLATFORM: x64
- provider: Environment
  name: cabl-win-x86
  on:
    branch: develop
    CONFIGURATION: Release
    PLATFORM: Win32
